spring:
  datasource:
    url: jdbc:h2:mem:patientdb;DB_CLOSE_DELAY=-1
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
server:
  port: 8081